/** Computing brand -> models used by title-based detection (sell step 1). */
export const COMPUTING_MODEL_SUGGESTIONS_FOR_DETECTION: Record<string, string[]> = {
  Dell: [
    "Dell XPS Series",
    "Dell Inspiron Series",
    "Dell Latitude Series",
    "Dell Vostro Series",
    "Dell Precision Series",
    "Dell G Series",
    "Dell Alienware Series",
    "OptiPlex Series",
    "Inspiron Desktop Series",
    "XPS Desktop Series",
    "Alienware Aurora Series",
  ],
  HP: [
    "EliteBook Series",
    "Pavilion Series",
    "Envy Series",
    "Spectre Series",
    "Victus Series",
    "Omen Series",
    "ZBook Series",
    "ProDesk Series",
    "EliteDesk Series",
    "Pavilion Desktop Series",
    "OMEN Desktop Series",
  ],
  Lenovo: [
    "ThinkPad Series",
    "IdeaPad Series",
    "Legion Series",
    "Yoga Series",
    "ThinkBook Series",
    "LOQ Series",
    "Miix Series",
    "Essential Series",
    "ThinkCentre Series",
    "IdeaCentre Series",
    "Legion Tower Series",
  ],
  Apple: ["MacBook Air", "MacBook Pro", "iMac Series", "Mac Mini Series", "Mac Studio Series"],
  Asus: [
    "ROG Zephyrus Series",
    "ROG Strix Series",
    "ROG Flow Series",
    "Zenbook Series",
    "Vivobook Series",
    "TUF Gaming Series",
    "ExpertBook Series",
    "ProArt Series",
    "Asus Desktop Series",
  ],
  Acer: [
    "Aspire Series",
    "Swift Series",
    "Nitro Series",
    "Predator Series",
    "Spin Series",
    "TravelMate Series",
    "Chromebook Series",
    "Vero Series",
    "Aspire Desktop Series",
    "Nitro Desktop Series",
    "Predator Desktop Series",
  ],
  MSI: ["Stealth Series", "Raider Series", "Titan Series", "Cyborg Series", "Katana Series", "Modern Series", "Prestige Series"],
  Microsoft: ["Surface Laptop Series", "Surface Pro Series", "Surface Studio Series", "Surface Book Series"],
};
