/**
 * Construction item (leaf) names by subcategory — mirrors CONSTRUCTION_REPAIR_CONFIG in sell/details.
 * Used only for title → hierarchy detection on the sell flow.
 */
export const CONSTRUCTION_LEAVES_BY_SUB: Record<string, string[]> = {
  Materials: [
    "Cement",
    "Steel & Metal",
    "Concrete & Precast",
    "Flooring Materials",
    "Construction Adhesive",
    "Pipes & Fittings",
    "PVC Pipes",
    "HDPE Pipes",
    "Water Tanks",
    "Fittings",
    "Roofing Materials",
    "Paints",
    "Paint Brushes, Rollers & Trays",
    "Tiles",
    "Ceramics",
    "Gypsum",
    "Glass",
    "Aluminum",
    "Marble",
    "Plasterboard",
    "Plasters",
    "Plywood",
    "Polystyrene",
    "Sand",
    "Rock & Gravel",
    "Sealants",
    "Tiles & Slabs",
    "Wallpaper",
    "Cables & Wires",
    "Switches",
    "Circuit Breakers",
    "Transformers",
    "Other",
  ],
  "Heavy Machinery": [
    "Excavators",
    "Loaders",
    "Bulldozers",
    "Graders",
    "Cranes",
    "Concrete Equipment",
    "Road Equipment",
    "Backhoe Loaders",
    "Tractors",
    "Concrete Pumps",
    "Forklifts",
    "Road Rollers",
    "Dumpers",
    "Wheel Loaders",
    "Concrete Mixers",
    "Boom Lifts",
    "Compactors",
    "Compressors",
    "Pallet Stackers",
    "Drilling Rigs",
    "Crushers",
    "Other",
  ],
  "Tools & Equipment": [
    "Power Tools",
    "Hand Tools",
    "Welding Machines",
    "Electrical Supplies",
    "Plumbing Supplies",
    "Safety Equipment",
    "DIY & Construction Accessories",
    "Other",
  ],
  Services: ["Construction Services", "Machinery Rental", "Engineering Services", "Other"],
  Other: ["Other"],
};
