/** Smartphone brand → models — aligned with sell/details SMARTPHONE_MODEL_SUGGESTIONS for title detection. */
export const SMARTPHONE_MODEL_SUGGESTIONS_FOR_DETECTION: Record<string, string[]> = {
  Apple: [
    "iPhone 6",
    "iPhone 6 Plus",
    "iPhone 6s",
    "iPhone 6s Plus",
    "iPhone 7",
    "iPhone 7 Plus",
    "iPhone 8",
    "iPhone 8 Plus",
    "iPhone X",
    "iPhone XR",
    "iPhone XS",
    "iPhone XS Max",
    "iPhone 11",
    "iPhone 11 Pro",
    "iPhone 11 Pro Max",
    "iPhone 12",
    "iPhone 12 Mini",
    "iPhone 12 Pro",
    "iPhone 12 Pro Max",
    "iPhone 13",
    "iPhone 13 Mini",
    "iPhone 13 Pro",
    "iPhone 13 Pro Max",
    "iPhone 14",
    "iPhone 14 Plus",
    "iPhone 14 Pro",
    "iPhone 14 Pro Max",
    "iPhone 15",
    "iPhone 15 Plus",
    "iPhone 15 Pro",
    "iPhone 15 Pro Max",
    "iPhone 16",
    "iPhone 16 Plus",
    "iPhone 16 Pro",
    "iPhone 16 Pro Max",
    "Other",
  ],
  Samsung: [
    "Galaxy S6",
    "Galaxy S6 Edge",
    "Galaxy S7",
    "Galaxy S7 Edge",
    "Galaxy S8",
    "Galaxy S8+",
    "Galaxy S9",
    "Galaxy S9+",
    "Galaxy S10",
    "Galaxy S10+",
    "Galaxy S10e",
    "Galaxy S20",
    "Galaxy S20+",
    "Galaxy S20 Ultra",
    "Galaxy S21",
    "Galaxy S21+",
    "Galaxy S21 Ultra",
    "Galaxy S22",
    "Galaxy S22+",
    "Galaxy S22 Ultra",
    "Galaxy S23",
    "Galaxy S23+",
    "Galaxy S23 Ultra",
    "Galaxy S24",
    "Galaxy S24+",
    "Galaxy S24 Ultra",
    "Galaxy S25",
    "Galaxy S25+",
    "Galaxy S25 Ultra",
    "Galaxy A10",
    "Galaxy A20",
    "Galaxy A30",
    "Galaxy A50",
    "Galaxy A51",
    "Galaxy A52",
    "Galaxy A53",
    "Galaxy A54",
    "Galaxy A55",
    "Galaxy Z Fold3",
    "Galaxy Z Fold4",
    "Galaxy Z Fold5",
    "Galaxy Z Fold6",
    "Galaxy Z Flip3",
    "Galaxy Z Flip4",
    "Galaxy Z Flip5",
    "Galaxy Z Flip6",
    "Other",
  ],
  Xiaomi: [
    "Mi 9",
    "Mi 10",
    "Mi 11",
    "Xiaomi 12",
    "Xiaomi 12T",
    "Xiaomi 13",
    "Xiaomi 13T",
    "Xiaomi 14",
    "Xiaomi 14T",
    "Redmi Note 10",
    "Redmi Note 11",
    "Redmi Note 12",
    "Redmi Note 13",
    "Redmi Note 14",
    "POCO X3",
    "POCO X4",
    "POCO X5",
    "POCO X6",
    "POCO F3",
    "POCO F4",
    "POCO F5",
    "POCO F6",
    "Other",
  ],
  OnePlus: [
    "OnePlus 6",
    "OnePlus 6T",
    "OnePlus 7",
    "OnePlus 7 Pro",
    "OnePlus 8",
    "OnePlus 8 Pro",
    "OnePlus 9",
    "OnePlus 9 Pro",
    "OnePlus 10 Pro",
    "OnePlus 11",
    "OnePlus 12",
    "OnePlus 13",
    "OnePlus 14",
    "OnePlus 15",
    "Nord",
    "Nord 2",
    "Nord 3",
    "Nord 4",
    "Other",
  ],
  "Google Pixel": ["Pixel 4", "Pixel 5", "Pixel 6", "Pixel 6 Pro", "Pixel 7", "Pixel 7 Pro", "Pixel 8", "Pixel 8 Pro", "Pixel 9", "Pixel 9 Pro", "Other"],
  Tecno: [
    "Camon 15",
    "Camon 16",
    "Camon 17",
    "Camon 18",
    "Camon 19",
    "Camon 20",
    "Camon 30",
    "Spark 6",
    "Spark 7",
    "Spark 8",
    "Spark 9",
    "Spark 10",
    "Spark 20",
    "Spark 30",
    "Phantom X",
    "Phantom V Fold",
    "Other",
  ],
  Infinix: [
    "Hot 10",
    "Hot 11",
    "Hot 12",
    "Hot 20",
    "Hot 30",
    "Hot 40",
    "Hot 50",
    "Note 10",
    "Note 11",
    "Note 12",
    "Note 30",
    "Note 40",
    "Note 50",
    "Zero 20",
    "Zero 30",
    "Zero 40",
    "Other",
  ],
  itel: ["A16", "A23", "A56", "A60", "A70", "P36", "P38", "P40", "P55", "S16", "S17", "S23", "Other"],
  Huawei: ["P30", "P40", "P50", "P60 Pro", "Mate 30", "Mate 40", "Mate 50", "Nova 7i", "Nova 8i", "Nova 9", "Nova 10", "Nova 11i", "Nova 12i", "Pura 70", "Other"],
  Nokia: ["5.3", "6.1", "7.2", "G20", "G21", "G42", "XR21", "C30", "C31", "C32", "Other"],
  Vivo: ["V20", "V21", "V23", "V25", "V27", "V29", "V30", "Y20", "Y21", "Y33", "Y36", "Y100", "Other"],
  Oppo: ["A15", "A16", "A17", "A57", "A78", "A98", "Reno 8", "Reno 10", "Reno 11", "Reno 12", "Other"],
  Realme: ["C11", "C21", "C25", "C30", "C33", "C35", "C55", "C67", "C75", "11 Pro", "12 Pro", "Other"],
  Nothing: ["Phone (1)", "Phone (2)", "Phone (2a)", "Other"],
  Honor: ["X7", "X8", "X9a", "X9b", "X9c", "Magic5", "Magic6 Lite", "Magic7 Pro", "Other"],
  Motorola: ["Moto G Power", "Moto G Stylus", "Moto G84", "Moto G85", "Edge 30", "Edge 40", "Edge 50", "Other"],
};
