/** Vehicle brand → models — same catalog as sell/details BrandModelFields for title detection. */
export const VEHICLE_MODEL_SUGGESTIONS_FOR_DETECTION: Record<string, string[]> = {
  Toyota: [
    "Adventure",
    "Avalon",
    "Avanza",
    "Aygo",
    "Belta",
    "bZ3",
    "bZ4X",
    "C-HR",
    "Camry",
    "Carina",
    "Coaster",
    "Corolla",
    "Corolla Cross",
    "Corolla DX",
    "Corolla Executive",
    "Crown",
    "Fortuner",
    "HiAce (Abba Dulla / Dolphin)",
    "Highlander",
    "Hilux (Vigo / Revo / Invincible)",
    "Land Cruiser",
    "Land Cruiser (70 Series)",
    "Land Cruiser Prado",
    "Land Cruiser V8",
    "Mark II",
    "Platz",
    "Prius",
    "Raize",
    "RAV4",
    "Rush",
    "Starlet",
    "Tacoma",
    "Urban Cruiser",
    "Vitz",
    "Yaris",
  ],
  Nissan: ["Sunny", "Altima", "Sentra", "X-Trail", "Qashqai", "Patrol", "Navara", "Urvan"],
  Honda: ["Civic", "Accord", "City", "CR-V", "HR-V", "Pilot"],
  Suzuki: ["Alto", "Swift", "Dzire", "Celerio", "Baleno", "Ertiga", "Vitara", "Jimny", "S-Presso"],
  Hyundai: ["Elantra", "Accent", "Sonata", "Tucson", "Santa Fe", "Creta", "Palisade"],
  Kia: ["Rio", "Cerato", "K5", "Sportage", "Sorento", "Seltos"],
  Ford: ["Focus", "Fusion", "Escape", "Explorer", "Ranger", "F-150"],
  Chevrolet: ["Spark", "Aveo", "Cruze", "Malibu", "Captiva", "Equinox", "Silverado"],
  BMW: ["1 Series", "3 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X6"],
  "Mercedes-Benz": ["A-Class", "C-Class", "E-Class", "S-Class", "GLA", "GLC", "GLE", "GLS", "G-Class"],
  Audi: ["A3", "A4", "A6", "A8", "Q3", "Q5", "Q7", "Q8"],
  Volkswagen: ["Polo", "Golf", "Passat", "Tiguan", "Touareg"],
  Peugeot: ["208", "301", "308", "3008", "5008"],
  Renault: ["Kwid", "Logan", "Duster", "Koleos"],
  Mazda: ["Mazda 2", "Mazda 3", "Mazda 6", "CX-3", "CX-5", "CX-9"],
  Mitsubishi: ["Lancer", "Outlander", "Pajero", "Montero Sport", "L200"],
  Isuzu: ["D-Max", "MU-X"],
  Subaru: ["Impreza", "Legacy", "Forester", "Outback"],
  Lexus: ["RX", "NX", "LX", "GX", "ES", "IS"],
  Tesla: ["Model 3", "Model S", "Model X", "Model Y"],
  BYD: [
    "Dolphin",
    "Seagull",
    "Dolphin Surf",
    "Seal",
    "Seal U",
    "Sealion 5",
    "Sealion 6",
    "Sealion 7",
    "Seal 5 DM-i",
    "Seal 6 DM-i",
    "Destroyer 05",
    "Frigate 07",
    "Qin",
    "Qin Pro",
    "Qin Plus",
    "Qin L",
    "Han",
    "Han EV",
    "Han DM",
    "Han DM-i",
    "Tang",
    "Tang EV",
    "Tang DM",
    "Tang DM-i",
    "Song",
    "Song Pro",
    "Song Plus",
    "Song Max",
    "Song L",
    "Yuan",
    "Yuan Pro",
    "Yuan Plus",
    "Yuan Up",
    "Atto 2",
    "Atto 3",
    "e1",
    "e2",
    "e3",
    "e5",
    "e6",
    "e7",
    "D1",
    "M3",
    "M6",
    "F0",
    "F3",
    "F3DM",
    "F5",
    "F6",
    "G3",
    "G3R",
    "G5",
    "G6",
    "L3",
    "S6",
    "S7",
    "Surui",
    "Speedy",
    "Shark",
    "Shark 6",
    "Denza D9",
    "Denza N7",
    "Denza N8",
    "Yangwang U7",
    "Yangwang U8",
    "Yangwang U9",
    "Fangchengbao Bao 5",
    "Fangchengbao Bao 8",
  ],
  Chery: ["Arrizo 5", "Arrizo 6", "Tiggo 2", "Tiggo 4", "Tiggo 7", "Tiggo 8"],
  Geely: ["Emgrand", "Coolray", "Atlas"],
  Changan: ["Alsvin", "Eado", "CS35", "CS55", "CS75"],
  "Great Wall": ["Wingle", "Poer"],
  Haval: ["H2", "H6", "Jolion"],
  Dongfeng: ["Rich", "AX7"],
  GAC: ["GS3", "GS4", "GS8"],
  BAIC: ["X25", "X35", "BJ40"],
  FAW: ["V2", "V5", "Bestune T77"],
  Wuling: ["Hongguang Mini EV", "Almaz"],
  Denza: ["D9", "N7"],
  Foton: ["Tunland", "View"],
  JMC: ["Vigus", "Boarding"],
  Sinotruk: ["Howo"],
};
