/** Vehicle brand → models — same catalog as sell/details BrandModelFields for title detection. */
export const VEHICLE_MODEL_SUGGESTIONS_FOR_DETECTION: Record<string, string[]> = {
  Toyota: ["Corolla", "Yaris", "Vitz", "Camry", "RAV4", "Highlander", "Fortuner", "Land Cruiser", "Prado", "Hilux", "Hiace"],
  Nissan: ["Sunny", "Altima", "Sentra", "X-Trail", "Qashqai", "Patrol", "Navara", "Urvan"],
  Honda: ["Civic", "Accord", "City", "CR-V", "HR-V", "Pilot"],
  Suzuki: ["Alto", "Swift", "Dzire", "Celerio", "Baleno", "Ertiga", "Vitara", "Jimny", "S-Presso"],
  Hyundai: ["Elantra", "Accent", "Sonata", "Tucson", "Santa Fe", "Creta", "Palisade"],
  Kia: ["Rio", "Cerato", "K5", "Sportage", "Sorento", "Seltos"],
  Ford: ["Focus", "Fusion", "Escape", "Explorer", "Ranger", "F-150"],
  Chevrolet: ["Spark", "Aveo", "Cruze", "Malibu", "Captiva", "Equinox", "Silverado"],
  BMW: ["1 Series", "3 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X6"],
  "Mercedes-Benz": ["A-Class", "C-Class", "E-Class", "S-Class", "GLA", "GLC", "GLE", "GLS", "G-Class"],
  Audi: ["A3", "A4", "A6", "A8", "Q3", "Q5", "Q7", "Q8"],
  Volkswagen: ["Polo", "Golf", "Passat", "Tiguan", "Touareg"],
  Peugeot: ["208", "301", "308", "3008", "5008"],
  Renault: ["Kwid", "Logan", "Duster", "Koleos"],
  Mazda: ["Mazda 2", "Mazda 3", "Mazda 6", "CX-3", "CX-5", "CX-9"],
  Mitsubishi: ["Lancer", "Outlander", "Pajero", "Montero Sport", "L200"],
  Isuzu: ["D-Max", "MU-X"],
  Subaru: ["Impreza", "Legacy", "Forester", "Outback"],
  Lexus: ["RX", "NX", "LX", "GX", "ES", "IS"],
  Tesla: ["Model 3", "Model S", "Model X", "Model Y"],
  BYD: ["F3", "Qin", "Qin Plus", "Song", "Song Plus", "Song Pro", "Yuan Plus", "Yuan Up", "Tang", "Han", "Dolphin", "Seagull", "Seal"],
  Chery: ["Arrizo 5", "Arrizo 6", "Tiggo 2", "Tiggo 4", "Tiggo 7", "Tiggo 8"],
  Geely: ["Emgrand", "Coolray", "Atlas"],
  Changan: ["Alsvin", "Eado", "CS35", "CS55", "CS75"],
  "Great Wall": ["Wingle", "Poer"],
  Haval: ["H2", "H6", "Jolion"],
  Dongfeng: ["Rich", "AX7"],
  GAC: ["GS3", "GS4", "GS8"],
  BAIC: ["X25", "X35", "BJ40"],
  FAW: ["V2", "V5", "Bestune T77"],
  Wuling: ["Hongguang Mini EV", "Almaz"],
  Denza: ["D9", "N7"],
  Foton: ["Tunland", "View"],
  JMC: ["Vigus", "Boarding"],
  Sinotruk: ["Howo"],
};
